# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9dc15591d8444850d0c33cbf270a2e59206b3153425da036ef79468a7158252fa2bb567f707d2b415a5d6fc980fcea3c591748c7def1c165bb76c34d4157b0a

test:
  secret_key_base: 0d51887ebbb77af56ea2ea47f065e7dc77274d9900338746a34a836da6ecf4033b0dc1c537f17549a4b4b7d70cdb42c82ac4ea0a12979964375011dcc463c6a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
